name: new_version
description: Check if your user has the most recent version of your Flutter app.
version: 0.4.0
homepage: https://github.com/hamzamirai/new_version

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^8.0.3
  http: ^1.2.2
  html: ^0.15.4
  url_launcher: ^6.3.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
